FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

WORKDIR /app/cmd/sms_worker

RUN go build -o /sms_service main.go

FROM alpine:latest
COPY --from=builder /sms_service /sms_service

EXPOSE 3000

CMD ["/sms_service"]