FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .


RUN go build -o /sms_service ./cmd/sms_worker

FROM alpine:latest

COPY --from=builder /sms_service /sms_service

EXPOSE 3000
CMD ["/sms_service"]
