FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .


RUN go build -o /email_worker ./cmd/email_worker

FROM alpine:latest


COPY --from=builder /email_worker /email_worker

EXPOSE 3001
CMD ["/email_worker"]
