FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

WORKDIR /app/cmd/email_worker

RUN go build -o /app/email_service main.go

FROM alpine:latest
COPY --from=builder /app/email_service /email_service

EXPOSE 3001

CMD ["/email_service"]