email:
  provider: smtp
  smtp:
    host: localhost
    port: 1025
    username: user@gmail.com
    password: secret
    useAuth: true

sms:
  provider: twilio
  twilio:
    host: smtp.gmail.com
    port: 587
    username: user@gmail.com
    password: secret
    useAuth: true
