receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  tempo:
    endpoint: "tempo:3200"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [tempo]
