services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  api:
    build:
      context: .
      dockerfile: deployments/Dockerfile.api
    ports:
      - "8080:8080"
    env_file:
      - ".env"
    depends_on:
      - kafka
  email:
    build:
      context: .
      dockerfile: deployments/Dockerfile.email
    ports:
      - "3001:3001"
    environment:
      - KAFKA_BROKER=kafka:9092
    env_file:
      - ".env"
    depends_on:
      - kafka
  sms:
    build:
      context: .
      dockerfile: deployments/Dockerfile.sms
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BROKER=kafka:9092
    env_file:
      - ".env"
    depends_on:
      - kafka
