{
 "title": "Signalbus",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Metrics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_total_requests[1m])", "legendFormat": "__auto" },
    {
     "expr": "sum by (status) (http_total_requests)",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_request_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Metrics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_publish_success_total[1m]))\n\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(kafka_publish_failure_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(kafka_subscriber_success_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(kafka_subscriber_failure_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(notification_send_duration_seconds_sum[1m]) / rate(notification_send_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(notification_send_duration_seconds_bucket[5m])) by (le, provider, service))",
     "legendFormat": "__auto"
    },
    {
     "expr": "notification_send_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External API",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(external_api_success_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(external_api_failure_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(external_api_failure_total[5m])) / (sum(rate(external_api_failure_total[5m])) + sum(rate(external_api_success_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}